### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by piramiday** [sjmiller8182/tomatopy#1]
hi @sjmiller8182, I've just discovered this project and I would be happy to use it.
the problem is -- it does not look like it's working any more!

e.g. this small script:
```python3
from tomatopy import get_main_page_info as info
results = info('https://www.rottentomatoes.com/m/x2_xmen_united')
for item in results.items(): print(item)
```
manages to parse only the synopsis, while everything else returns `None`.

**is this project still alive?** if so, will you have time to update the regex for each parsing field?
if it is, I would be happy to get [version 0.2.0](https://github.com/sjmiller8182/tomatopy#planned-updates-for-020) with parsing for user reviews and tomatometer scores!

if this is dead, feel free to close this issue.
in that case, you might want to archive the repo or put a disclaimer in the main readme.
thanks! :raised_hand_with_fingers_splayed:

**Comment by sjmiller8182** [comment]
@piramiday,
Thanks for the note! At the moment, I am not able to make updates on this project due to other time commitments.
Contributions are welcome if you are up to making the fixes.

**Comment by piramiday** [comment]
no worries, I understand -- I'd suggest to mark the repo as archived, then, or add a note mentioning that you won't update it further.
